<div class="">
  <h1>ユーザ一覧</h1>
  <?php foreach ($users as $key => $user) : ?>
    <div>
      --------------------------------------------------
      <p>
        <?php echo "id: {$user['id']}" ; ?>
      </p>
      <p>
        <?php echo "firstname: {$user['firstname']}"; ?>
      </p>
      <p>
        <?php echo "lastname: {$user['lastname']}"; ?>
      </p>
      <p>
        <?php echo "age: {$user['age']}"; ?>
      </p>
      <p>
        <?php echo "email: {$user['email']}"; ?>
      </p>
      <a href=<?php echo "/users/{$user['id']}" ;?> > 詳細ページ</a>
      <a href=<?php echo "/users/{$user['id']}/edit" ;?> >編集ページ</a>
      <form action=<?php echo "/users/{$user['id']}"  ;?> method="post">
        <input type="hidden" name="_METHOD" value="DELETE"/>
        <input type="submit" value="削除"/>
      </form>
  </div>

 <?php endforeach; ?>
 --------------------------------------------------
</div>
<a href="/users/new">ユーザ追加</a>
