
<form action="/users" method="post">
  <div class="">
    <label for="">firstname</label>
    <input type="text" name="firstname" placeholder="firstname を入力">
  </div>
  <div class="">
    <label for="">lastname</label>
    <input type="text" name="lastname" placeholder="lastname を入力">
  </div>
  <div class="">
    <label for="">email</label>
    <input type="text" name="email" placeholder="email を入力">
  </div>
  <div class="">
    <label for="">age</label>
    <input type="age" name="age" placeholder="age を入力">
  </div>

  <div class="">
    <label for="">location</label>
    <input type="location" name="location" placeholder="location を入力">
  </div>
  <input type="submit" method_exists value="送信">
</form>