<div class="">
  <p>
      <?php echo "id: {$user['id']}" ; ?>
      </p>
      <p>
        <?php echo "firstname: {$user['firstname']}"; ?>
      </p>
      <p>
        <?php echo "lastname: {$user['lastname']}"; ?>
      </p>
      <p>
        <?php echo "age: {$user['age']}"; ?>
      </p>
      <p>
        <?php echo "email: {$user['email']}"; ?>
      </p>
      <a href=<?php echo "/users" ;?> >戻る</a>
      <a href="">編集ページ</a>
      <a href="">削除</a>
</div>